/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['consolidation.js']) {
  _$jscoverage['consolidation.js'] = [];
}
_$jscoverage['consolidation.js'].source = [];
